backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "clothes"
    label: "Houda Boutique Products"
    # This 'file' setting ensures all data is saved into one file
    file: "data/clothes.json"
    format: "json"
    extension: "json"
    fields:
      - { label: "Clothing Item Name", name: "name", widget: "string" }
      - { label: "Price ($)", name: "price", widget: "number", value_type: "float" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
